### ISSUE TITLE
Soulstorm crash pie

### ISSUE THREAD

**Issue by bluelightning32** [GastronomistGuild/ExpandedFoods#40]
Mixing Soulstorm Slop and Soulstorm Refined in a pie causes a crash on the client. When the first ingredient is added, it is a single ingredient type pie, and nothing crashes. The pie can be finished with either ingredient, as long as that's the only ingredient.

However, if both types of Soulstorm brew are added to the pie, it crashes. In order to mix ingredients, they must be from the same food category, and then it becomes a mixed pie of that food category. For example, adding turnips and onions to a pie creates a vegetable pie. Both kinds of Soulstorm brew have the NoNutrition category. The crash occurs because the model is missing for NoNutrition pie.
```
Running on 64 bit Linux (Fedora Linux 40 (Workstation Edition)) [Kernel 6.10.9.200] with 11797 MB RAM
Game Version: v1.19.8 (Stable)
10/2/2024 10:23:12AM: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.1, game@1.19.8, expandedfoods@1.7.1, hudclock@3.4.0, gourmand@1.2.3, creative@1.19.8, survival@1.19.8
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Vintagestory.GameContent.MealMeshCache.GetPieMesh(ItemStack pieStack, ModelTransform transform) in VSSurvivalMod\Systems\Cooking\MealMeshCache.cs:line 149
   at Vintagestory.GameContent.BlockEntityPie.loadMesh() in VSSurvivalMod\BlockEntity\BEPie.cs:line 364
   at Vintagestory.GameContent.BlockEntityPie.OnInteract(IPlayer byPlayer) in VSSurvivalMod\BlockEntity\BEPie.cs:line 218
   at Vintagestory.GameContent.BlockPie.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockPie.cs:line 488
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 864
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 444
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 102
   at Vintagestory.Client.ClientProgram..ctor(String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.Client.ClientProgram.Main(String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 47
   at VintagestoryClientLinux.ClientLinux.Main(String[] args) in VintagestoryClient\Linux\ClientLinux.cs:line 9
```

More specifically, the crash occurs on the following line, because NoNutrition has value -1, and `fillingFoodCat` is set to that. `pieMixedFillingTextures` is an array, and index -1 is invalid for arrays.
```c#
                    fillingTextureLoc = equal ? stackprops[1]?.Texture : pieMixedFillingTextures[(int)fillingFoodCat];
```

This crash could cause a denial of service for public servers. Anyone who ever gets within range of the pie will have a crashed client.

The simplest fix is to set `allowMixing: false` in the `inPieProperties` for Soulstorm Slop and Soulstorm Refined.

**Comment by Lazula** [comment]
Fixed by recent changes to pies.
