### ISSUE TITLE
Crash when navigating Handbook

### ISSUE THREAD

**Issue by hstde** [GastronomistGuild/ExpandedFoods#41]
Hi.

When I navigate to the muffin page in the handbook and specifically click on the part-baked muffin, the game crashes. I didn't notice any other crashes so far.

The exception that get's logged is this:

`Running on 64 bit Windows 10.0.19045.0 with 32592 MB RAM
Game Version: v1.19.8 (Stable)
2024-10-10 10:06:58: Critical error occurred
Loaded Mods: aculinaryartillery@1.2.1, bettersticks@1.1.0, buzzwords@1.7.0, chiseltools@1.12.10, decor@1.1.6, entitiesinteract@1.0.11, caninae@1.0.16, capreolinae@1.1.5, casuariidae@1.0.8, dinornithidae@0.7.0, machairodontinae@1.0.9, manidae@1.0.2, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, HangingOilLamps@1.0.1, HumanSkinTones@0.0.3, millwright@1.1.7, TA_plainsandvalleys@1.0.5, primitivesurvival@3.6.5, saltandsands@1.0.2, scraps@1.1.1, she1fish@1.2.1, Swordz@1.19.3, TVSM@0.0.1, game@1.19.8, zoombuttonreborn@1.9.0, animalcages@3.0.3, animationmanagerlib@0.8.8, bedspawnv2@1.2.0, betterfirepit@1.1.4, commonlib@2.5.0-rc.2, composter@1.1.0, danatweaks@3.2.2, expandedfoods@1.7.2, extrainfo@1.8.1, foodshelves@1.3.1, hudclock@3.4.0, kegrevivedagain@1.1.0, knapster@2.11.2, lichenredux@1.8.3, mif@1.0.1, moreanimals@1.3.5, morepiles@1.5.0, norottinghides@1.0.0, oneroof@1.0.2, rivers@3.1.0, simplestep@1.1.7, storageoptions@1.0.2, thecritterpack@0.9.1, creative@1.19.8, survival@1.19.8, bullseye-continued@2.5.8, extraoverlays@1.4.0, cookie12000stickbeam@1.1.0, stonequarry@3.3.1
System.Exception: Can't create itemstack without collectible!
   at Vintagestory.API.Common.ItemStack..ctor(CollectibleObject collectible, Int32 stacksize) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 198
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.addCreatedByInfo(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor, ItemStack stack, List`1 components, Single marginTop, Boolean haveText) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 1137
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.GetHandbookInfo_Patch2(CollectibleBehaviorHandbookTextAndExtraInfo this, ItemSlot inSlot, ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor)
   at Vintagestory.GameContent.GuiHandbookItemStackPage.GetPageText(ICoreClientAPI capi, ItemStack[] allStacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 117
   at Vintagestory.GameContent.GuiHandbookItemStackPage.ComposePage(GuiComposer detailViewGui, ElementBounds textBounds, ItemStack[] allstacks, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 111
   at Vintagestory.GameContent.ModSystemSurvivalHandbook.onComposePage(GuiHandbookPage page, GuiComposer detailViewGui, ElementBounds textBounds, ActionConsumable`1 openDetailPageFor) in VSSurvivalMod\Systems\Handbook\SurvivalHandbook.cs:line 97
   at Vintagestory.GameContent.GuiDialogHandbook.initDetailGui() in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 258
   at Vintagestory.GameContent.GuiDialogHandbook.OpenDetailPageFor(String pageCode) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 314
   at Vintagestory.GameContent.CollectibleBehaviorHandbookTextAndExtraInfo.<>c__DisplayClass18_0.<addCreatedByInfo>b__16(ItemStack cs) in VSSurvivalMod\Systems\Handbook\CollectibleBehaviorHandbookTextAndExtraInfo.cs:line 1053
   at Vintagestory.API.Client.ItemstackTextComponent.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\Richtext\ItemstackTextComponent.cs:line 101
   at Vintagestory.API.Client.GuiElementRichtext.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Text\GuiElementRichtext.cs:line 527
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 494
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 560
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 390
   at Vintagestory.Client.NoObf.ClientMain.UpdateMouseButtonState(EnumMouseButton button, Boolean down) in VintagestoryLib\Client\ClientMain.cs:line 1919
   at Vintagestory.Client.SystemHotkeys.OnPrimaryMouseButton(KeyCombination mb) in VintagestoryLib\Client\Systems\Player\Hotkeys.cs:line 50
   at Vintagestory.Client.HotkeyManager.TriggerHotKey(KeyEvent keyEventargs, IWorldAccessor world, IPlayer player, Boolean allowCharacterControls, Boolean isGlobal, Boolean fallBack, Boolean keyup) in VintagestoryLib\Client\HotkeyManager.cs:line 431
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDownRaw(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1846
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 198
   at OpenTK.Windowing.Desktop.NativeWindow.MouseButtonCallback(Window* window, MouseButton button, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
`

If you need any other information, please let me know.

**Comment by IrcDirk** [comment]
Yep same on my side.
